#!/usr/bin/env python

# This is the default requests hello world modified to work with
# datawire service discovery. There is a point to using the default
# requests hello world as our example. We want our stuff to be easy to
# work with stuff people already know how to use and are familiar
# with. We aren't telling people how to use web services, they already
# know this. We are showing people how what they already know can fit
# into a microservices architecture.

# The changes to add in discovery are shown below. Currently the API
# is being used in "long form" mode, we can/will streamline/add
# convenience for common scenarios, but first and most important we
# need to get the end-to-end scenario working so we can identify any
# sleeping dragons.

import requests

# Start discovery related changes.
from discovery import Discovery, Node
from util import Datawire
disco = Discovery("http://disco.datawire.io")
disco.token = Datawire.getToken()
disco.start()
url = disco.resolve('hello-flask').address
# End discovery related changes.

r = requests.get(url)
print r.status_code
print r.headers['content-type']
print r.encoding
print r.text
